import { Annotation } from "@langchain/langgraph";
import type { Research } from "../../domain/contracts.js";
import type { SearxngSearchResult } from "../../infra/search/searxngClient.js";
import type { SummarizationResult } from "../summarization/summarizer.js";

export type RmsPhase =
  | "freshness"
  | "queryPlanning"
  | "searching"
  | "queryRewriting"
  | "reranking"
  | "summarizing"
  | "persisting";

/**
 * LangGraph state definition — shared across freshnessChecker, searcher,
 * summarizer, and persister nodes.
 *
 * Uses `Annotation.Root` (same pattern as GMS) for typed graph state
 * with reducers and defaults.
 *
 * @see GMS's `GmsStateAnnotation` in `src/app/state/schema.ts`
 */
export const RmsStateAnnotation = Annotation.Root({
  /** The research subject/query being investigated. */
  subject: Annotation<string>(),
  /** Optional tenant isolation ID. */
  tenantId: Annotation<string | undefined>(),
  /** Whether to bypass cache and force a fresh search. */
  forceRefresh: Annotation<boolean>({
    reducer: (_prev, next) => next,
    default: () => false,
  }),
  /** Maximum number of search results to retrieve. */
  maxResults: Annotation<number>({
    reducer: (_prev, next) => next,
    default: () => 10,
  }),
  /** Freshness threshold in days. */
  freshnessDays: Annotation<number>({
    reducer: (_prev, next) => next,
    default: () => 7,
  }),
  /** Cached research if found (populated by freshnessChecker). */
  cachedResearch: Annotation<Research | undefined>(),
  /** Whether cached research is still fresh. */
  isFresh: Annotation<boolean>({
    reducer: (_prev, next) => next,
    default: () => false,
  }),
  /** Raw search results from SearXNG. */
  searchResults: Annotation<SearxngSearchResult[]>({
    reducer: (_prev, next) => next,
    default: () => [],
  }),
  /** LLM summarization output. */
  summarization: Annotation<SummarizationResult | undefined>(),
  /** Final persisted research entry. */
  research: Annotation<Research | undefined>(),
  /** Source of the result: cache, web, or cache+web (refreshed). */
  source: Annotation<"cache" | "web" | "cache+web">({
    reducer: (_prev, next) => next,
    default: () => "web",
  }),
  /** Current workflow phase. */
  currentPhase: Annotation<RmsPhase>({
    reducer: (_prev, next) => next,
    default: () => "freshness",
  }),
  /** Error message if any node fails. */
  error: Annotation<string | undefined>(),
  /** Distributed trace ID for observability. */
  traceId: Annotation<string | undefined>(),
  /** Optional metadata to attach to the research entry. */
  metadata: Annotation<Record<string, unknown> | undefined>(),
  /** Number of query rewrites performed (agentic RAG loop). */
  rewriteCount: Annotation<number>({
    reducer: (_prev, next) => next,
    default: () => 0,
  }),
  /** The original subject before any query rewrites. */
  originalSubject: Annotation<string | undefined>(),
  /** The rewritten query (set by queryRewriter when relevance is low). */
  rewrittenQuery: Annotation<string | undefined>(),
  /** Search result relevance score from the query rewriter. */
  relevanceScore: Annotation<number | undefined>(),
  /** Planned search queries generated by the query planner node. */
  plannedQueries: Annotation<string[]>({
    reducer: (_prev, next) => next,
    default: () => [],
  }),

  /** Accumulated token usage across all LLM calls (planner, rewriter, summarizer). */
  tokenUsage: Annotation<{ promptTokens: number; completionTokens: number }>({
    reducer: (prev, next) => ({
      promptTokens: prev.promptTokens + next.promptTokens,
      completionTokens: prev.completionTokens + next.completionTokens,
    }),
    default: () => ({ promptTokens: 0, completionTokens: 0 }),
  }),
});

export type RmsState = typeof RmsStateAnnotation.State;
